[package]
name = "vm-translator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
criterion = "0.5.1"

[[bench]]
name = "cli_bench"
harness = false
